#!/bin/bash

function minify {
    minifyjs -m --level=1 -i $1/$1.js > .js-cache/$1.min.js
}

echo Building JS..
minify submit_event
minify user_create
minify login
minify admin
minify event
minify search
minify index
minify about
minify events_table